name: 'Deploy to Staging'

on:
  push:
    branches: [develop, staging]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Тестирование для staging
  test-staging:
    runs-on: ubuntu-latest
    name: 'Staging Tests'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Build for staging
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.STAGING_API_URL }}
          VITE_ENVIRONMENT: staging
          NODE_ENV: production

  # Деплой на staging
  deploy-staging:
    needs: test-staging
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for staging
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.STAGING_API_URL }}
          VITE_ENVIRONMENT: staging
          VITE_SENTRY_DSN: ${{ secrets.STAGING_SENTRY_DSN }}
          NODE_ENV: production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,prefix=staging-
            type=sha,prefix=staging-{{branch}}-
            type=raw,value=staging-latest

      - name: Build and push Docker image for staging
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to staging server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_VPS_HOST }}
          username: ${{ secrets.STAGING_VPS_USERNAME }}
          key: ${{ secrets.STAGING_VPS_SSH_KEY }}
          port: ${{ secrets.STAGING_VPS_PORT }}
          script: |
            echo "🚀 Deploying to staging..."

            # Логинимся в registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

            # Останавливаем и удаляем текущий staging контейнер
            docker stop vibesplit-pwa-staging || true
            docker rm vibesplit-pwa-staging || true

            # Запускаем новый staging контейнер
            docker run -d \
              --name vibesplit-pwa-staging \
              --restart unless-stopped \
              -p 8081:80 \
              -v /var/log/vibesplit-staging:/var/log/nginx \
              -e NODE_ENV=production \
              -e VITE_ENVIRONMENT=staging \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging-latest

            # Проверяем здоровье staging
            sleep 15
            if curl -f http://localhost:8081/health; then
              echo "✅ Staging deployment successful"
            else
              echo "❌ Staging deployment failed"
              docker logs vibesplit-pwa-staging
              exit 1
            fi

            # Очищаем старые образы
            docker image prune -f

      - name: Notify staging deployment
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#staging-deployments'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            VibeSplit Staging Deployment: ${{ job.status }}
            Branch: ${{ github.ref_name }}
            Environment: staging
            URL: https://staging.vibesplit.com
